name: mena
description: Mena platform

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependency_overrides:
  intl: ^0.18.0
dependencies:
  flutter:

    sdk: flutter

  flutter_localizations:
    sdk: flutter


#  mena_live_webrtc:
#    git:
#      url: https://github.com/MozafarAlali93/mena_live_webrtc.git
#      ref: master # branch name

  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.1
  intl_phone_number_input: ^0.7.0+2
  firebase_core: ^2.4.1
  flutter_svg: ^1.0.1
  flutter_screenutil: ^5.9.0
  persistent_bottom_nav_bar_v2: ^4.2.4
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.1
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+1
  pull_down_button: ^0.1.0-beta.6
  flutter_staggered_grid_view: ^0.6.2
  staggered_grid_view_flutter: ^0.0.4
  dio: ^5.2.0
  cached_network_image: ^3.2.1
  figma_squircle: ^0.5.3
  lottie: ^2.2.0
  file_picker: ^5.2.5
  pin_code_fields: ^7.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.1.0
  json_store: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  video_player: ^2.4.7
  google_maps_flutter: ^2.2.1
  flutter_rating_bar: ^4.0.1
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.11.0
  multi_select_flutter: ^4.1.2
  url_launcher: ^6.1.10
  transparent_image: ^2.0.0
  bloc: ^8.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  audio_session: ^0.1.13
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  pull_to_refresh: ^2.0.0
  google_maps_place_picker_mb: ^3.0.1
  flutter_cache_manager: ^3.3.0
  flutter_slidable: ^2.0.0
  #  extended_text: ^9.1.2
  easy_image_viewer: ^1.2.0
  just_audio: ^0.9.31
  audio_video_progress_bar: ^0.11.0
  geolocator: ^9.0.2
  extended_text: ^11.1.0
  table_calendar: ^3.0.9
  spinner_date_time_picker: ^0.0.8
  flutter_datetime_picker_plus: ^2.1.0
#  gallery_picker: ^0.4.5
  preload_page_view: ^0.2.0
  syncfusion_flutter_pdfviewer: ^21.1.38
  http: ^0.13.5
  custom_marker: ^1.0.0
  map_launcher: ^2.5.0+1
  outline_gradient_button: ^2.0.1+1
  dropdown_button2: ^2.1.2
  flutter_switch: ^0.3.2
  add_2_calendar: ^2.2.3
  socket_io_client: ^1.0.2
  flutter_html:
#  html: ^0.15.4
#  flutter_html: ^2.2.1
#  flutter_html: ^3.0.0-beta.2
#  maps_launcher: ^2.2.0
#  place_picker: ^0.10.0
  keyboard_emoji_picker: ^1.0.1
  whiteboard: ^0.0.2
  webview_flutter: ^4.2.2
  screen_recorder: ^0.2.0
  m_toast: ^0.1.5
  like_button: ^2.0.5
  share_plus: ^6.0.0
  flutter_webrtc: ^0.9.34
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/mena.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  #generators
  hive_generator:
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/addedbyzein/
    - assets/images/
    - assets/icons/messenger/
    - assets/images/public/
    - assets/svg/
    - assets/json/
    - assets/svg/icons/
    - assets/svg/meetings/
    - assets/svg/icons/profile/
    - assets/flags/
    - assets/video/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: Visby
      fonts:
        - asset: assets/fonts/visby-cufonfonts/VisbyLight.otf

    - family: VisbyBold
      fonts:
        - asset: assets/fonts/visby-cufonfonts/VisbyBold.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf

    - family: Crimson
      fonts:
        - asset: assets/fonts/crimson/CrimsonPro-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf

    - family: LatoBold
      fonts:
        - asset: assets/fonts/lato/Lato-Bold.ttf
